### ISSUE TITLE
Errors when listing & deleting files

### ISSUE THREAD

**Issue by so0k** [cogcmd/aws-s3#1]
Cog version: 1.0-beta2
Relay version: 1.0-beta2

Listing buckets works
`!bucket list my-pattern`
```
+------------------------------+-------------------------+
| Name                         | Creation Date           |
+------------------------------+-------------------------+
| bucket-1-my-pattern          | 2016-12-16 09:15:47 UTC |
| bucket-2-my-pattern          | 2016-12-16 09:15:25 UTC |
+------------------------------+-------------------------+
```

Deleting buckets also works, but the following commands fail:

`!file list bucket-1-my-pattern`
```
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to bucket-1-my-pattern.s3-ap-southeast-1.amazonaws.com:443 (getaddrinfo: Try again) (Seahorse::Client::NetworkingError)
   from /usr/lib/ruby/2.3.0/net/http.rb:879:in`block in connect'
   from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
...
   from /home/bundle/lib/s3/client.rb:44:in`list_files'
...
```

`file destroy bucket-1-my-pattern path/to/file/2016_12_19_171321.csv`
```
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to bucket-1-my-pattern.s3-ap-southeast-1.amazonaws.com:443 (getaddrinfo: Try again) (Seahorse::Client::NetworkingError)
...
   from /home/bundle/lib/s3/client.rb:63:in `destroy_file'
```

**Comment by so0k** [comment]
something wrong in https://github.com/aws/aws-sdk-ruby ? I went through the issue list and couldn't find anything relevant.. the latest release is 2.7.4 while current s3 bundle has 2.6.11, maybe I shld try updating the image..

**Comment by davejlong** [comment]
@so0k I'm going to close this issue for now, as it has not had any activity in 6 months. If there is still an issue that you're observing that we should investigate, feel free to re-open.

**Comment by so0k** [comment]
we're not using the s3 module currently, so can't say if it's fixed or not
